### ISSUE TITLE
Why we use minReadySeconds 10 Minutes

### ISSUE THREAD

**Issue by anpingli** [openshift/cluster-logging-operator#69]
@ewolinetz  Why the next fluent pod wait for  10 Min? The only reason I can imagine is connection issue to Elastic search?
https://github.com/openshift/cluster-logging-operator/blob/d9644ccc5a18ea97606cbf0645e1db8bcc3647b5/pkg/utils/utils.go#L282

**Comment by jcantrill** [comment]
@anpingli 
You identifying a connection issue to Elasticsearch is reasonable to me based on the [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/).  We recently extended the period of time which the platform roles back a deployment because of issues with AWS releasing storage from the previous pod.  It was advised this could be as much as 20 minutes.  Thinking through fluentd, however, I would expect for us to be able to actually set this to zero since Fluent should just spin trying to reconnect.  There is nothing in particular that would suggest we need to revert to the previous version

**Comment by ewolinetz** [comment]
I believe the reason this is bumped up is so that we can extend past the default `300` sec that the scheduler uses before culling a pod that isn't yet `Ready`

**Comment by jcantrill** [comment]
@ewolinetz the question though is what would keep this pod from being ready?  Would the fact that you can not  contact Elasticsearch cause the pod to not be ready?  I don't think so.  I believe the only issue would be the run.sh script failing.  Can we remove this setting?

**Comment by ewolinetz** [comment]
`run.sh` failing shouldn't cause the pod to not be ready -- it would be `Ready` by the time that is running.

I looked up what this spec actually is used for (and the context in which we're using it) and we should still keep it, though I would be open for decreasing the value. It is used for a rolling update, we make sure that the new pod is ready for that duration before removing the old one [1]

[1] https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds

**Comment by jcantrill** [comment]
Since the pod spec has no readiness probe doesnt this mean the pod will almost always be ready immediately assuming the container doesnt terminate? I'm not sure how extending beyond the default (5 min) adds any value.

**Comment by ewolinetz** [comment]
> I'm not sure how extending beyond the default (5 min) adds any value.

Per that link, the default is `0` though

**Comment by jcantrill** [comment]
> > I'm not sure how extending beyond the default (5 min) adds any value.
> 
> Per that link, the default is `0` though

In that case maybe we should consider dropping it to 60s or the like since that should be enough time for the pod to 'start'

**Comment by jcantrill** [comment]
resolved with https://github.com/openshift/cluster-logging-operator/commit/6d4d62c1227c3b0117bfe01885eea410dfd6449e

**Comment by jcantrill** [comment]
Modified in https://github.com/openshift/cluster-logging-operator/commit/6d4d62c1227c3b0117bfe01885eea410dfd6449e
