### ISSUE TITLE
Suggestions for forwardTemplate in release-4.6/pkg/generators/forwarding/fluentd/templates.go

### ISSUE THREAD

**Issue by git001** [openshift/cluster-logging-operator#703]
Hi.

The commended link should point to output forward.
```
https://github.com/openshift/cluster-logging-operator/blob/release-4.6/pkg/generators/forwarding/fluentd/templates.go#L582
# https://docs.fluentd.org/v1.0/articles/in_forward <= wrong
# https://docs.fluentd.org/output/forward
```

Please can you add the following options to the template and configurable.

* require_ack_response
* tls_client_private_key_passphrase

The "tls_client_private_key_path" is not yet active. I don't think that a `tls_client_cert_path` without a key make sense.

How about to check if a key is defined and then activate both lines, something like this.

```
{{ if  (ne {{  .SecretPath "tls.key"}} "" ) }}
tls_client_private_key_path {{ .SecretPath "tls.key"}}
tls_client_cert_path {{ .SecretPath "tls.crt"}}
{{ if  (ne {{  .SecretPath "tls_client_private_key_passphrase"}} "" ) }}
tls_client_private_key_passphrase {{ .SecretPath "tls_client_private_key_passphrase"}}
{{ end }}
{{ end }}
```

It would be also very helpful to activate the compression by default with `compress gzip`

**Comment by jcantrill** [comment]
> Hi.
> 
> The commended link should point to output forward.

Pull requests are welcome
 
> * require_ack_response
> * tls_client_private_key_passphrase
> 
> The "tls_client_private_key_path" is not yet active. I don't think that a `tls_client_cert_path` without a key make sense.
> 

The templates of fluent configuration are intentionally opinionated as the goal is to provide log collection with minimal effort and tuning as possible.  We are choosing to not expose every available knob in order to avoid replicating what is already possible with fluent config. If you have need to modify these values
* edit the CL instance and set it to Unmanaged
* modify the fluent configmap to your needs

Additional tuning is available as described here: https://github.com/openshift/enhancements/blob/master/enhancements/cluster-logging/fluentd-tuning.md

> It would be also very helpful to activate the compression by default with `compress gzip`

Please open any feature requests here:  https://issues.redhat.com
