### ISSUE TITLE
MERGE_JSON_LOG Does not work in OCP 4.6? 

### ISSUE THREAD

**Issue by Channyboy** [openshift/cluster-logging-operator#842]
In 4.3 the command :
```
oc set env ds/fluentd MERGE_JSON_LOG=true
```
Allowed for the cluster logging's fluentd instances to merge JSON formatted logs from the application container to the parent JSON payload as described in [this doc in master](https://github.com/openshift/cluster-logging-operator/blob/master/docs/unmanaged_configuration.md) (after setting to unmanaged)

In 4.6 this no longer seems to work.
I see that https://github.com/openshift/origin-aggregated-logging/issues/1492 was asking to disable it and the related PR https://github.com/openshift/origin-aggregated-logging/pull/1493 sets it to false by default. But that was already the expected behavior in 4.3. I don't see any issue that explicitly disables it the `MERGE_JSON_LOG` functionality altogether?

The need for the the ability to merge JSON logs is important when using [OpenLiberty](https://openliberty.io/) as it produces JSON logs to console/std-out. Without the ability to merge the server's JSON output it is interpreted as one string for the `message` key. The specific scenario I'm running is when using the (Cluster) Log Forwarder to forward to an external log solution.

This causes relevant information from Open Liberty to not be accessible. Was this intended? [This doc in master](https://github.com/openshift/cluster-logging-operator/blob/master/docs/unmanaged_configuration.md)  indicates that it is still viable? Also I don't see any mention of  this features removal inn the 4,4, 4.5 nor 4.6 release notes for Open shift.

**Comment by jcantrill** [comment]
The was explicitly disabled in 4.x because of issues with unbounded keys causing ES to fail.  The workaround you mention is non-functional after preferring operator controlled config and deployments.  Any change will be stomped by the operator as intended.  I don't recall if this var has any significant meaning in 4.3 but a work around for  you may be to set the ClusterLogging instance to "unmanaged" and then apply the env var to the collector daemonset.  Alternatively you are free to go unmanaged and edit the config to meet your requirements.

Note setting to unmanaged means you will:

* be managing the deployment yourself
* Not receive updates unless you set it back to managed
* Your changes would need to be re-applied if going back to "unmanaged"

There is a formal effort to reintroduce this capability as identified by: https://github.com/openshift/enhancements/pull/518

**Comment by Channyboy** [comment]
Hi @jcantrill  Thank you for the reply.
I have set cluster logging to `unmanaged` and applied the environment variable. I've also forced restart the fluentd pods.
But it isn't working in 4.6

**Comment by Channyboy** [comment]
I should mention I am only able to spawn/use a OCP 4.6.6
The 4.3 OCP that I am able to spawn is 4.3.40.
I've been able to test with 4.4 and 4.5 long before (I do not recall  what versions were available then for me to use).

I tested the 4.3.40 and 4.6.6 in succesion/parallel.

**Comment by jcantrill** [comment]
> Hi @jcantrill Thank you for the reply.
> I have set cluster logging to `unmanaged` and applied the environment variable. I've also forced restart the fluentd pods.
> But it isn't working in 4.6. The JSON logs are not merged to the parent payload compared to 4.3.

It's because as you can see, intentionally, there are no (few) environment variables honoured in 4.6 config https://github.com/openshift/cluster-logging-operator/blob/release-4.6/pkg/generators/forwarding/fluentd/fluent_conf_test.go#L295 unlike 4.3 https://github.com/openshift/cluster-logging-operator/blob/release-4.3/pkg/generators/forwarding/fluentd/fluent_conf_test.go#L274

4.6 requires you to set the stack to unmanaged and manually edit the config
